# Generated by Django 4.2.1 on 2023-07-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=50, null=True)),
                ('Discription', models.CharField(blank=True, max_length=50, null=True)),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
