# Generated by Django 4.2.1 on 2023-08-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NiceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='Discription',
            new_name='Description',
        ),
    ]
