# Generated by Django 4.2.1 on 2023-08-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NiceApp', '0004_remove_categorydb_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Message', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='nmedia')),
            ],
        ),
    ]
