# Generated by Django 4.2.1 on 2023-09-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_commentdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentdb',
            new_name='Reviewdb',
        ),
    ]
