# Generated by Django 3.2.10 on 2024-03-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20240312_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Price',
            new_name='TotalPrice',
        ),
    ]
